spring:
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

logging:
  level:
    root: info
